#!/bin/bash
echo "************************************************************************************"
echo "***You must install all these tools to complete your Windows 10 pentesting build****"
echo "***ATTENTION: This Script Does Not Install Tools. It only provides links for tools**"
echo "************************************************************************************"
echo "HxD (hex editor) - http://mh-nexus.de/en/hxd"
echo "Evade (used for AV evasion) - https://www.securepla.net/antivirus-now-you-see-me-now-you-dont/"
echo "Hyperion (used for AV evasion) - http://www.nullsecurity.net/tools/binary.html"
echo "Hyperion (continued) - Needs Win Compiler http://sourceforge.net/projects/mingw"
echo "Hyperion (continued) - run make in extracted directory"
echo "MetaSploit - http://www.Metasploit.com/"
echo "Nexpose/Nessus"
echo "NMAP - http://nmap.org/download.html"
echo "oclHashcat - http://hashcat.net/oclhashcat/#downloadlatest"
echo "Evil Foca - http://www.informatica64.com/evilfoca/"
echo "Cain and Abel - http://www.oxid.it/cain/html"
echo "Burp Suite Pro - http://portswigger.net/burp/download.html"
echo "Nishang - https://code.google.com/p/nishang/downloads/list"
echo "PowerSploit - https://github.com/mattifestation/PowerSploit/archive/master.zip"
echo ""
echo ""
echo "************************************************************************************"
echo "***Now Install These Addons in Firefox - ****"
echo "************************************************************************************"
echo "Firefox Addons:"
echo "-----------Web Developer Addon - https://addons.mozilla.org/en-US/firefox/addon/web-developer/"
echo "-----------Tamper Data Addon - https://addons.mozilla.org/en-US/firefox/addon/tamper-data/"
echo "-----------Foxy Proxy Addon - https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/"
echo "-----------User Agent Switcher Addon - https://addons.mozilla.org/en-US/firefox/addon/user-agent-switcher/"
